# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "FiveDeen::App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

# url to javascript library containing the symbol definitions. relative to www root
symbols: /javascripts/symbols.js

# default sequence file without layout
sequence:
    json: /home/perldev/workspace/FiveDeen-App/sequence.json

# user string location
string:
    json: /home/perldev/workspace/FiveDeen-App/string.json

# json file containing the symbol sequence and the default layout as defined by set_linear_points
maps:
    json: /home/perldev/workspace/FiveDeen-App/maps.json
    div: 8
    offset: 50
    width: 825
    height: 825 
    
# symbol library
lib:
    json: /home/perldev/workspace/FiveDeen-App/symbols.json 
    
# the default font map
font:
    json: /home/perldev/workspace/FiveDeen-App/font.json       
